version: '3.4'

services:

  database:
    image: postgres:12
    container_name: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=exploration
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    volumes:
      - .:/usr/local/src 
  
  nginx:
    image: nginx
    container_name: nginx
    ports: 
      - 80:80
    volumes:
      - ./nginx/public:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d

  backend:
    build: backend
    image: backend:python
    container_name: backend
    env_file: .env
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/local/src/
