version: '3.4'

services:

  database:
    image: postgres:12
    container_name: database
    ports:
      - 2345:5432
    environment:
      - POSTGRES_DB=exploration
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    volumes:
      - .:/usr/local/src 
  
  nginx:
    image: nginx
    container_name: nginx
    ports: 
      - 8080:80
    volumes:
      - ./frontend:/usr/share/nginx/html

  builder:
    image: python:3
    container_name: builder
    ports:
      - 5000:5000
    volumes:
      - .:/usr/local/src
    entrypoint: bash
    working_dir: /usr/local/src