version: '3.4'

services:

  database:
    image: postgres:12
    container_name: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=exploration
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
  
  nginx:
    build: nginx
    image: nginx:ready
    container_name: nginx
    environment: 
      - BACKEND_URL=http://backend:5000/
      - PORT=8080
    ports: 
      - 8080:8080
    volumes:
      - ./nginx/public:/usr/share/nginx/html
      - ./nginx:/usr/local/src/nginx

  backend:
    build: backend
    image: backend:python
    container_name: backend
    environment: 
      - DATABASE_URL=postgres://dev:dev@database:5432/exploration
      - PORT=5000
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/local/src/
