name: CD

on:
  push:
    branches:
      - deployed

jobs:

  backend:
    name: deploy backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_PYTHONSTACK}}
        heroku_app_name: "python-stack-backend"
        heroku_email: "eric.mignot+pythonstack@gmail.com"
        usedocker: true
        appdir: backend
        docker_heroku_process_type: web
        stack: container
        healthcheck: "https://python-stack-backend.herokuapp.com/data"
        delay: 33

  nginx:
    needs: backend
    name: deploy nginx
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_PYTHONSTACK}}
        heroku_app_name: "python-stack"
        heroku_email: "eric.mignot+pythonstack@gmail.com"
        usedocker: true
        appdir: nginx
        docker_heroku_process_type: web
        stack: container
        healthcheck: "https://python-stack.herokuapp.com/api/data"
        delay: 33
        
